### ISSUE TITLE
You missspelelled Qendolin

### ISSUE THREAD

**Issue by Qendolin** [lilypuree/ConnectibleChains#13]
My nickname is spelled "Qendolin" not "quendolin"

https://github.com/lilypuree/ConnectibleChains/blob/a8ef0de19ec77ee517ea0a4d49201027601bdaa7/src/main/resources/META-INF/mods.toml#L13
https://github.com/lilypuree/ConnectibleChains/blob/a8ef0de19ec77ee517ea0a4d49201027601bdaa7/src/main/java/com/lilypuree/connectiblechains/entity/ChainCollisionEntity.java#L45

**Comment by Mysticpasta1** [comment]
I will remove the extra u

**Comment by Mysticpasta1** [comment]
will be fixed in 1.19.2, 1.19.4, and the upcoming 1.20.1 branch
