### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by ghost** [lilypuree/ConnectibleChains#2]
Would love to see support for:
**Charm**
- Gold Chain

**Forbidden & Arcanus**
- Iron Chain
- Arcane Golden Chain

...and any other mods that add chains if they exist!

**Comment by TrueVenomized** [comment]
The Charm Gold Chain would be really nice, I agree!

**Comment by lilypuree** [comment]
Mod support will be added once the fabric mod supports it.
