### ISSUE TITLE
Crash on 1.16.5

### ISSUE THREAD

**Issue by BenjaminCap2** [lilypuree/ConnectibleChains#3]
Placing a chain on a fence on a 1.16.5 server ( java 8 mohist #468 ) cause a crash with this message ( all players are disconnected too ) : 
https://imgur.com/a/7tUVsiR

**Comment by BenjaminCap2** [comment]
Exact log when the  crash happen : https://pastebin.com/c6Kutvxf
Forge version used : 36.1.4 and 36.1.0

**Comment by lilypuree** [comment]
1.16.5 is no longer supported, sorry
