### ISSUE TITLE
1.16.5 Multiplayer - Chains not display after disconnect/reconnect for client

### ISSUE THREAD

**Issue by Axelouuu-dev** [lilypuree/ConnectibleChains#5]
Hey

I play with Connectible Chains, Optifine and other mods on multiplayer server.
My friend have put a chain between two cobble walls and if I am connected to the server after the chains are put, I can't see them but my friend can. 

Here a screenshot with a chain placed before I connect to the server on the left , and chains placed after I connect on the right.
![issue chain connectible](https://user-images.githubusercontent.com/19538750/129399712-ae83c444-091c-4faf-b59a-7363b0011d64.png)

A last thing, when I attack an invisible chain, I can ear chain sound.

**Comment by raffle2** [comment]
Same problem here :c

**Comment by Nebula240** [comment]
Bump, same issue here

**Comment by SkullDiamond** [comment]
sad that there is no fix yet :(

**Comment by lilypuree** [comment]
1.16.5 is no longer supported, won't fix.
