### ISSUE TITLE
[1.18] Chain stretches after 1 block with Complementary Shaders

### ISSUE THREAD

**Issue by anarisis** [lilypuree/ConnectibleChains#7]
When loaded with Complementary Shaders, after about a block the texture of a single link is stretched out for the remainder of the chain's length.

![2022-01-25_19 02 08](https://user-images.githubusercontent.com/934897/151096996-ac048317-d116-4eb6-8029-b6cf101c2556.png)

**Comment by lilypuree** [comment]
I cannot provide support for shaders.
